-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 20:54:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema luizcarlosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema luizcarlosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luizcarlosdb` DEFAULT CHARACTER SET utf8 ;
USE `luizcarlosdb` ;

-- -----------------------------------------------------
-- Table `luizcarlosdb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luizcarlosdb`.`cliente` (
  `idcli` INT NOT NULL AUTO_INCREMENT,
  `nomecli` VARCHAR(100) NOT NULL,
  `enderecocli` VARCHAR(90) NULL DEFAULT NULL,
  `telefonecli` VARCHAR(45) NOT NULL,
  `emailcli` VARCHAR(85) NULL DEFAULT NULL,
  PRIMARY KEY (`idcli`),
  UNIQUE INDEX `id_UNIQUE` (`idcli` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `luizcarlosdb`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luizcarlosdb`.`os` (
  `os` INT NOT NULL AUTO_INCREMENT,
  `data_os` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `equipamento` VARCHAR(500) NOT NULL,
  `defeito` VARCHAR(1010) NOT NULL,
  `servico` VARCHAR(5000) NULL DEFAULT NULL,
  `tecnico` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(10,3) NOT NULL,
  `idcliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`os`),
  -- UNIQUE INDEX `os_UNIQUE` (`os` ASC) VISIBLE,
  INDEX `icliente_idx` (`idcliente` ASC),
  CONSTRAINT `IDCLIENTE`
    FOREIGN KEY (`idcliente`)
    REFERENCES `luizcarlosdb`.`cliente` (`idcli`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `luizcarlosdb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luizcarlosdb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(500) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `email` VARCHAR(65) NULL DEFAULT NULL,
  `telefone` VARCHAR(80) NOT NULL,
  `login` VARCHAR(14) NOT NULL,
  `senha` VARCHAR(95) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
